# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(default='White', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='favoritefood',
            field=models.CharField(default='bone', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='favoritetoy',
            field=models.CharField(default='ball', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(default='male', max_length=1000),
            preserve_default=False,
        ),
    ]
