# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Breed'),
            preserve_default=False,
        ),
    ]
